package view;

import dao.PerguntaDao;
import dao.RespostaDao;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Pergunta;
import model.Resposta;



//package view;

/**
 *
 * @author jhond
 */
public class Quizz extends javax.swing.JInternalFrame {

    PerguntaDao perguntaDao;
    RespostaDao respostaDao;
    List<Pergunta> listaPergunta;
    List<Resposta> listaResposta;
    int contador = 0;
    
    public Quizz() throws SQLException{
        perguntaDao = new PerguntaDao();
        respostaDao = new RespostaDao();
        initComponents();
        this.setVisible(true);
            listaPergunta = perguntaDao.ListaPergunta();
            lblPergunta.setText(listaPergunta.get(contador).getDescricao());
            listaResposta = respostaDao.ListaResposta(listaPergunta.get(contador).getId());
            rb_01.setText(listaResposta.get(0).getDescricao());
            rb_02.setText(listaResposta.get(1).getDescricao());
            rb_03.setText(listaResposta.get(2).getDescricao());
            rb_04.setText(listaResposta.get(3).getDescricao());
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_pergunta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rb_01 = new javax.swing.JRadioButton();
        rb_02 = new javax.swing.JRadioButton();
        rb_03 = new javax.swing.JRadioButton();
        rb_04 = new javax.swing.JRadioButton();
        lbl_resposta = new javax.swing.JLabel();
        btn_corrigir = new javax.swing.JButton();
        btn_proximo = new javax.swing.JButton();
        lblPergunta = new javax.swing.JLabel();

        setName("Quizz"); // NOI18N

        jPanel1.setName("pnl_pergunta"); // NOI18N

        jLabel1.setText("Pergunta");

        buttonGroup1.add(rb_01);
        rb_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_01MouseClicked(evt);
            }
        });
        rb_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_01ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_02);

        buttonGroup1.add(rb_03);

        buttonGroup1.add(rb_04);

        btn_corrigir.setText("Corrigir");
        btn_corrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_corrigirActionPerformed(evt);
            }
        });

        btn_proximo.setText("Proximo");
        btn_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_03)
                    .addComponent(rb_02)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lbl_resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbl_pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rb_04)
                    .addComponent(rb_01))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_corrigir)
                .addGap(55, 55, 55)
                .addComponent(btn_proximo)
                .addGap(64, 64, 64))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_pergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(rb_01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_02)
                .addGap(29, 29, 29)
                .addComponent(rb_03)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_resposta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_04)
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_corrigir)
                    .addComponent(btn_proximo))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Quizz");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proximoActionPerformed

        lbl_resposta.setText("");
        buttonGroup1.clearSelection();
        contador = contador + 1;

        if (listaPergunta.size() > contador) {

            try {

                lbl_pergunta.setText(listaPergunta.get(contador).getDescricao());
                listaResposta = respostaDao.ListaResposta(listaPergunta.get(contador).getId());

                rb_01.setText(listaResposta.get(0).getDescricao());
                rb_02.setText(listaResposta.get(1).getDescricao());
                rb_03.setText(listaResposta.get(2).getDescricao());
                rb_04.setText(listaResposta.get(3).getDescricao());

            } catch (SQLException ex) {
                  Logger.getLogger(Quizz.class.getName()).log(Level.SEVERE, null, ex);

            }

        } else {

            JOptionPane.showMessageDialog(null, "Fim das Questoes");
            btn_proximo.setEnabled(false);
        }
    }//GEN-LAST:event_btn_proximoActionPerformed

    private void btn_corrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_corrigirActionPerformed

        if (rb_01.isSelected()) {

            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(0).getId()) {

                lbl_resposta.setText("Acertou");

            } else {

                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }

        }

        if (rb_02.isSelected()) {

            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(1).getId()) {

                lbl_resposta.setText("Acertou");

            } else {

                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }

        }

        if (rb_03.isSelected()) {

            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(2).getId()) {

                lbl_resposta.setText("Acertou");

            } else {

                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }

        }

        if (rb_04.isSelected()) {

            if (listaPergunta.get(contador).getResposta_certa() == listaResposta.get(3).getId()) {

                lbl_resposta.setText("Acertou");

            } else {

                JOptionPane.showMessageDialog(null, listaPergunta.get(contador).getComentario());
            }

        }
    }//GEN-LAST:event_btn_corrigirActionPerformed

    private void rb_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_01ActionPerformed

          
    }//GEN-LAST:event_rb_01ActionPerformed

    private void rb_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_01MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_01MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_corrigir;
    private javax.swing.JButton btn_proximo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JLabel lbl_pergunta;
    private javax.swing.JLabel lbl_resposta;
    private javax.swing.JRadioButton rb_01;
    private javax.swing.JRadioButton rb_02;
    private javax.swing.JRadioButton rb_03;
    private javax.swing.JRadioButton rb_04;
    // End of variables declaration//GEN-END:variables
}
